### ISSUE TITLE
linux/nvme.h has been renamed in linux 4.4

### ISSUE THREAD

**Issue by floppym** [rhinstaller/efivar#37]
When building with linux 4.4 headers, one will hit this:

```
gcc -O2 -g -Werror -Wall -Wsign-compare -Wstrict-aliasing -std=gnu11 -fshort-wchar -fPIC -flto -fvisibility=hidden -D_GNU_SOURCE -I/home/floppym/src/efivar/src/include/efivar/  -Wmaybe-uninitialized   -c -o linux.o linux.c
linux.c:25:24: fatal error: linux/nvme.h: No such file or directory
compilation terminated.
```

See kernel commit 9d99a8dda154f38307d43d9c9aa504bd3703d596.

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=9d99a8dda154f38307d43d9c9aa504bd3703d596

**Comment by woutershep** [comment]
I don't think that error is related to the listed commit but merely that you seem to be missing the linux headers. Atleast my linux headers of 4.4 seems to include a linux/nvme.h when doing `make headers_install`

However that linux/nvme.h that i have doesn't define all the needed things anymore since that mentioned commit. I think the error that you meant to paste was:
```
linux.c: In function 'eb_nvme_ns_id':
linux.c:48:27: error: 'NVME_IOCTL_ID' undeclared (first use in this function)
  uint64_t ret = ioctl(fd, NVME_IOCTL_ID, NULL);
                           ^
linux.c:48:27: note: each undeclared identifier is reported only once for each function it appears in

```
Instead that one is in the new uapi/linux/nvme_ioctl.h which is not installed through `make headers_install`.

**Comment by floppym** [comment]
Gentoo's linux-headers-4.4 packaging includes several patches. One of them changes headers_install to include nvme_ioctl.h instead of nvme.h. This patch is pending review on LKML.

https://lkml.org/lkml/2016/1/10/332

I guess we will have to see how this turns out in linux-4.5.

**Comment by floppym** [comment]
The patch got merged on the kernel master branch.

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a9cf8284b45110a4d98aea180a89c857e53bf850

**Comment by floppym** [comment]
I'm applying this patch downstream; if you find the solution acceptable, feel free to merge it.

https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/efivar/files/0.21-nvme_ioctl.h.patch

**Comment by vathpela** [comment]
Thanks, I've pulled this in to master.
